[package]
name = "libvips"
version = "0.1.0"
authors = ["bongole <bongole2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffi_helpers = "0.2.0"
libvips-sys = { path = "../libvips-sys" }
